import Link from "next/link"
import styles from "./Nav.module.css"
import Container from './Home.module.css'


export const metadata = {
  title: 'Portofolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head />
      <body className={Container.body}>
      <nav className={styles.NavBar}>
            <div className={styles.Logo}>
              <h1>Miereureu</h1>
            </div>
            <div className={styles.List}>
              <Link className={styles.ListStyle} href={"/"} passHref>Home</Link>
              <Link className={styles.ListStyle} href={"/About"} passHref>About</Link>
              <Link className={styles.ListStyle} href={"/Project"} prefetch={false}>Project</Link>
              <Link className={styles.ListStyle} href={"/Contact"} passHref>Contact</Link>
            </div>
        </nav>
        { children }
        </body>
    </html>
  )
}
